-- Google Calendar 手動同期 Phase 1

-- duration_minutes 制約を >= 0 に緩和（0分保存バグ修正）
alter table public.schedule_items
  drop constraint if exists schedule_items_duration_positive;
alter table public.schedule_items
  add constraint schedule_items_duration_nonneg check (duration_minutes >= 0);

-- Google Calendar イベントID列
alter table public.schedule_items
  add column if not exists google_event_id text;

-- ユーザー×イベントIDの複合ユニークインデックス（upsertのonConflict用）
create unique index if not exists schedule_items_user_google_event_idx
  on public.schedule_items (user_id, google_event_id);

-- 将来の自動同期用: Googleトークン保管テーブル
create table if not exists public.user_google_tokens (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  access_token  text,
  refresh_token text,
  expires_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint user_google_tokens_user_id_unique unique (user_id)
);

alter table public.user_google_tokens enable row level security;

create policy "google_tokens_owner_select" on public.user_google_tokens
  for select to authenticated using (auth.uid() = user_id);

create policy "google_tokens_owner_insert" on public.user_google_tokens
  for insert to authenticated with check (auth.uid() = user_id);

create policy "google_tokens_owner_update" on public.user_google_tokens
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "google_tokens_owner_delete" on public.user_google_tokens
  for delete to authenticated using (auth.uid() = user_id);
