-- schedule_items テーブル: 決まった時間にやること
create table if not exists public.schedule_items (
  id bigint generated by default as identity primary key,
  time text not null,
  title text not null,
  duration_minutes int not null default 30,
  notify_minutes_before int not null default 0,
  created_at timestamptz not null default now(),
  constraint schedule_items_time_format check (time ~ '^[0-2][0-9]:[0-5][0-9]$'),
  constraint schedule_items_duration_positive check (duration_minutes > 0),
  constraint schedule_items_notify_nonneg check (notify_minutes_before >= 0)
);

create index if not exists schedule_items_time_idx on public.schedule_items (time);

alter table public.schedule_items enable row level security;

drop policy if exists "schedule_anon_select" on public.schedule_items;
create policy "schedule_anon_select"
  on public.schedule_items for select
  to anon, authenticated
  using (true);

drop policy if exists "schedule_anon_insert" on public.schedule_items;
create policy "schedule_anon_insert"
  on public.schedule_items for insert
  to anon, authenticated
  with check (true);

drop policy if exists "schedule_anon_update" on public.schedule_items;
create policy "schedule_anon_update"
  on public.schedule_items for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "schedule_anon_delete" on public.schedule_items;
create policy "schedule_anon_delete"
  on public.schedule_items for delete
  to anon, authenticated
  using (true);

insert into public.schedule_items (time, title, duration_minutes, notify_minutes_before) values
  ('07:00', 'ストレッチ', 15, 5),
  ('09:00', 'チームMTG', 30, 10),
  ('10:00', '集中作業タイム', 120, 10),
  ('12:00', '昼休み', 60, 0),
  ('14:00', '1on1 ミーティング', 30, 10),
  ('17:00', '今日の振り返り', 15, 5),
  ('19:00', 'ジョギング', 30, 0);
