-- tasks テーブル: 今日やるべきこと
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  tag text,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- 並び順を id 昇順で固定するためのインデックス（実質 PK で十分だが明示）
create index if not exists tasks_id_idx on public.tasks (id);

-- RLS 有効化（認証未実装MVP用、anon に select/update を許可）
alter table public.tasks enable row level security;

drop policy if exists "tasks_anon_select" on public.tasks;
create policy "tasks_anon_select"
  on public.tasks for select
  to anon, authenticated
  using (true);

drop policy if exists "tasks_anon_update" on public.tasks;
create policy "tasks_anon_update"
  on public.tasks for update
  to anon, authenticated
  using (true)
  with check (true);

-- 初期データ
insert into public.tasks (title, tag, done) values
  ('企画書の修正を完了する', '仕事', false),
  ('牛乳とパンを買う', null, false),
  ('レポートのレビュー依頼', '仕事', true),
  ('田中さんにメール返信', null, false);
